-- +goose Up
ALTER TABLE users REPLICA IDENTITY FULL;
ALTER TABLE subscriptions REPLICA IDENTITY FULL;

-- +goose Down
ALTER TABLE users REPLICA IDENTITY DEFAULT;
ALTER TABLE subscriptions REPLICA IDENTITY DEFAULT;